version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Logging in to Docker Registry...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

      - export IMAGE_REPO_NAME="tws-online-shop-app-demo"
      - export IMAGE_NAME="$DOCKER_REGISTRY_USERNAME/$IMAGE_REPO_NAME"

      # 🔑 IMPORTANT FIX: Disable Docker BuildKit
      - export DOCKER_BUILDKIT=0

      - echo "Image name is $IMAGE_NAME"

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_NAME:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $IMAGE_NAME:latest
